// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyR9D6Iw5c26O14YlYet5bO3500gb-c1c',
    appId: '1:509987013132:web:5f8e26e6df3baffd982429',
    messagingSenderId: '509987013132',
    projectId: 'recipe-app-d0f56',
    authDomain: 'recipe-app-d0f56.firebaseapp.com',
    storageBucket: 'recipe-app-d0f56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeC9-OBHOoy8pY37JAuR42N-8eSqa18s0',
    appId: '1:509987013132:android:e59571a945779ed5982429',
    messagingSenderId: '509987013132',
    projectId: 'recipe-app-d0f56',
    storageBucket: 'recipe-app-d0f56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIxLYxK7xarYuAs23BeNHirvX4aHGJWU',
    appId: '1:509987013132:ios:834ea300ec502c48982429',
    messagingSenderId: '509987013132',
    projectId: 'recipe-app-d0f56',
    storageBucket: 'recipe-app-d0f56.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
